### ISSUE TITLE
Checkboxes are requiring intitialization with Javascript

### ISSUE THREAD

**Issue by DanAtShenTech** [thetarkus/django-semanticui-forms#10]
In [Checkbox Usage](http://semantic-ui.com/modules/checkbox.html#/usage) it says that checkboxes do not require Javascript in order to function.  Your current rendering of checkboxes requires that the boxes be initialized with JS.  Might it be a good idea to have a form variable to allow us to determine how we want checkboxes to be rendered?

**Comment by thetarkus** [comment]
In the `example` app, checkboxes aren't initialized with Javascript and seem to work fine.  I even tested disabling Javascript completely.  I can't reproduce this one.

**Comment by Chris-ZA** [comment]
Checkboxes are working fine on my side without any JS initialization.  

@DanAtShenTech Can you you not check them at all?

**Comment by DanAtShenTech** [comment]
In a Semantic-UI based app that uses tabs (with the content of each tab the same type of Django form), I find that the checkbox on the first tab is able to be checked without JS initialization, but all tabs other than the first cannot be checked.
