### ISSUE TITLE
Layout Requested

### ISSUE THREAD

**Issue by DanAtShenTech** [thetarkus/django-semanticui-forms#14]
A co-worker asked if django-semanticui-forms has layout capability like [django-material does](https://github.com/2947721120/django-material#layout).  It would be very useful to be able to do layout like this in the form class rather than having to iterate through fields.  Any possibility of seeing this implemented?

**Comment by thetarkus** [comment]
This looks like a good idea to me

**Comment by DanAtShenTech** [comment]
Thanks.  I'm hopeful you can implement it.  With SUI's nice layout capability at both the field level and the grid level, it seems like it should be pretty straightforward for someone with your experience.

**Comment by DanAtShenTech** [comment]
Outstanding work!
