### ISSUE TITLE
Placement of classes in forms.py

### ISSUE THREAD

**Issue by DanAtShenTech** [thetarkus/django-semanticui-forms#15]
I am rendering forms with the {% render_form form_name %} tag, so I would like to be able to add additional SUI classes to the rendered components in forms.py (specifically, I am trying to enhance a dropdown to be a "search" dropdown).  When I place the "search" class on the field in forms.py, django-semanticui-forms is placing the class on the hidden input and not the `<div class="ui selection dropdown">` as needed:

    widgets = {
        'location': forms.Select(attrs={'class':'search'})
    }

If I use the django-semanticui-forms helper "_field_class" in place of just "class", it places the search class on the field div that wraps the dropdown, not the dropdown div.  Is there a way to do what I want to do within the existing release, or would this be something that needs a fix?  Perhaps an additional "_component_class" helper that would always place additional classes on the component's wrapper div?  Another example where this could be needed would be:

    <div class="ui input">
      <input type="text" placeholder="Search...">
    </div>

in which you might want to place another class on the wrapper div such as "disabled " or "loading".

We are rendering a lot of SUI forms and getting a lot of use from this library.  Thank you.

**Comment by thetarkus** [comment]
For those specialized fields like BooleanField and ChoiceField/Dropdowns, I believe you can add a `_style` attribute with the value of `search`

I'm not near my development machine so I can't try it out for you, but let me know if it works for you!

**Comment by DanAtShenTech** [comment]
That did it for the dropdown.  Thank you!
