### ISSUE TITLE
How to render icon inside search selection dropdown?

### ISSUE THREAD

**Issue by DanAtShenTech** [thetarkus/django-semanticui-forms#18]
I am using the following for a search selection field as you suggested doing in issue 17, and I am setting this inside `widgets={}` in forms.py:
 `"my_field": forms.TextInput(attrs={"_style": "search", "_override": "Select"})`
The dropdown icon is rendered on the right side of the field instead of the search icon.  If I do:
`"cover_stock": forms.TextInput(attrs={"_style": "search", "_override": "Select", "_icon": "search"})`
then nothing changes in the rendering - the dropdown icon is still rendered inside the `<input>`, not the search icon.  Fortunately, everything else looks right in the rendering and the search field behaves properly, but how can I replace the dropdown icon with the search icon?

**Comment by thetarkus** [comment]
Good idea.
Add `{"_dropdown_icon": "search"}` to your attributes.
