### ISSUE TITLE
ModelChoiceField does not render as a dropdown

### ISSUE THREAD

**Issue by samkuehn** [thetarkus/django-semanticui-forms#2]
I would be cool if the ModelChoiceField rendered as semantic-ui dropdown (like choices) instead of a standard select field.

**Comment by thetarkus** [comment]
Good idea! I'll get this in tonight, it requires some slight modification `render_choicefield` function.

**Comment by thetarkus** [comment]
Added!

**Comment by samkuehn** [comment]
Awesome!  Thanks so much.  I will check it out in the morning.
