### ISSUE TITLE
Checkbox error display points to nothing

### ISSUE THREAD

**Issue by Chris-ZA** [thetarkus/django-semanticui-forms#5]
Hi,

Is it possible to change the error that is displayed for the checkbox field?  See image:

![checkbox error](https://cloud.githubusercontent.com/assets/4954241/23586569/8a970134-01a0-11e7-858b-f3e425a16564.png)

The arrow points up to nothing.  Not sure if you can change the arrow for the checkbox field only to point left by adding the "left" class to the label?  If not, maybe move the error to below the field or perhaps just move the error to below the field entirely - like the other errors.

Thanks!

**Comment by thetarkus** [comment]
Absolutely, by making the checkbox inline by default (which will come with #7) will fix this.
