### ISSUE TITLE
Hidden fields render visible

### ISSUE THREAD

**Issue by DanAtShenTech** [thetarkus/django-semanticui-forms#6]
If the Django form contains fields of type [HiddenInput](https://docs.djangoproject.com/en/1.10/ref/forms/widgets/#hiddeninput) (and, I suppose, probably MultipleHiddenInput as well), the fields are not rendered as hidden.  It would be great if this could be fixed soon.  It is the one problem that is keeping me from fully implementing django-semanticui-forms.  I've worked around the problem for now by using my own template and rendering hidden and visible fields separately by hand [like this](https://docs.djangoproject.com/en/1.10/topics/forms/#looping-over-hidden-and-visible-fields) and doing an include of my form-rendering template, but of course I'd rather just be able to do {% render_form form %}.

**Comment by thetarkus** [comment]
Thanks for spotting this out.

**Comment by DanAtShenTech** [comment]
Outstanding!  Thank you for the quick turnaround!
