### ISSUE TITLE
Inline fields

### ISSUE THREAD

**Issue by DanAtShenTech** [thetarkus/django-semanticui-forms#7]
I need to render fields as [inline so that the label is beside the field instead of above it](http://semantic-ui.com/collections/form.html#inline).  Ideally there would be two ways to do this: a Django forms variable (or render_form parameter) and a variable for individual fields.  I have actually implemented it with an individual field variable ( _inline="true"), but I'm pretty new to Django and so haven't yet had time to work through how to do the whole form within the django-semanticui-forms library.  Would you be able to implement this request for these two options soon?  Or would you like me to submit a pull request for my _inline implementation?

**Comment by DanAtShenTech** [comment]
Any thoughts on a {% render_form inline %} option?

**Comment by thetarkus** [comment]
Try out `{% render_form form_class _inline=1 %}`
