### ISSUE TITLE
Django forms empty_label not rendering in dropdown

### ISSUE THREAD

**Issue by DanAtShenTech** [thetarkus/django-semanticui-forms#9]
If I set the empty_label parameter in a form in forms.py, AND if the field is required, then it seems I should be able to handle things with the first code below and that django-semantic-ui should take care of rendering the empty_label value as the valueless option in the dropdown.  Instead, I have to inject the empty value by hand as shown in the second set of code below.

class MyForm(ModelForm):
        ........
        self.fields[my_field'].empty_label = 'Entire Job'
        self.fields['my_field'].queryset = MyStep.objects.all()

class MyForm(ModelForm):
        ........
        self.fields[my_field'].empty_label = 'Entire Job'
        self.fields['my_field'].choices = (('', 'Entire Job'),) + tuple(MyStep.objects.all().values_list('id', 'name'))

**Comment by thetarkus** [comment]
This was originally a design choice.  The dropdown's placeholder is replaced with the blank value dashes that I hate, so in turn I implemented empty values in a different way, overlooking this specifically.  I can see the usefulness of it for others though.

So what I can do is display the `empty_label` as long as the label is not the blank value dashes. ("---------", I hate those dashes!) If it is that specific number of dashes or None, no value empty value will be shown.

Do you think that would work for you?

**Comment by thetarkus** [comment]
I went through with that idea.

**Comment by DanAtShenTech** [comment]
Absolutely.  The empty_label is just for that purpose - to be there as the empty choice instead of dashes.  Looking very forward to using your new implementation of this. Thanks!
